#!/bin/sh

DB='spider.sqlite'
REGEX_EMAIL='([a-zA-Z][0-9a-zA-Z_\-\.]+@[a-zA-Z]+(\.[a-zA-Z]+)+)'

insert_email()
{
    local sql="insert into email(email,url) values('$1','$2')"

    eval sqlite3 $DB \"$sql\"
}

URL="$1"
FILE="$2"

eval grep -roI -P \"$REGEX_EMAIL\" $FILE | while read email url; do insert_email $email `echo $FILE | awk -F/ '{print $1}'`; done
